### ISSUE TITLE
Ustream URLs don't all match

### ISSUE THREAD

**Issue by beardypig** [beardypig/streamlink#1]
The Ustream plugin doesn't match http://www.ustream.tv/channel/st-mary-s-rattlers-live

**Comment by TheSneakySniper** [comment]
Can't you just copy over the regex from the original plugin?

**Comment by beardypig** [comment]
It is the same regex and it works for me, but there is a difference Exception generated for that URL. 
```
streamlink -l debug http://www.ustream.tv/channel/st-mary-s-rattlers-live
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/st-mary-s-rattlers-live
Traceback (most recent call last):
  File ".virtualenvs/streamlink/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.0.1', 'console_scripts', 'streamlink')()
  File "streamlink/src/streamlink_cli/main.py", line 902, in main
    handle_url()
  File "streamlink/src/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "streamlink/src/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "streamlink/src/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "streamlink/src/streamlink/plugin/plugin.py", line 230, in streams    ostreams = self._get_streams()
  File "streamlink/src/streamlink/plugins/ustreamtv.py", line 336, in _get_streams
    ws.connect().recv_command()
  File "streamlink/src/streamlink/plugins/ustreamtv.py", line 60, in recv_command
    return self._callbacks[data[u"cmd"]](self, **data)
  File "streamlink/src/streamlink/plugins/ustreamtv.py", line 330, in handle_module_info
    if stream_metadata.get("streamType") == "flv/segmented":
AttributeError: 'unicode' object has no attribute 'get'
```

**Comment by beardypig** [comment]
The stream was offline when I tried it. Need to test it when it's online again.
